module.exports.data = [ 
    { id: "1", 
    name: "Bud Light", 
    description: "American-Style Lager", 
    rating: 4.9,
    image: "https://wikiliq.org/wp-content/uploads/2021/02/Bud-Light.jpeg",
    date: "05-10-1982",
    price: 26.99 },
    { id: "2", 
    name: "Stella Artois", 
    description: "Pale Lager",
    rating: 5.0,
    image: "https://wikiliq.org/wp-content/uploads/2021/02/Stella-Artois.jpeg", 
    date: "01-22-1926",
    price: 18.62 },
    { id: "3", 
    name: "New Belgium Fat Tire Amber Ale", 
    description: "Amber/Red Ale",
    rating: 5.0,
    image: "https://wikiliq.org/wp-content/uploads/2021/02/New-Belgium-Fat-Tire-Amber-Ale.jpeg", 
    date: "11-22-1991",
    price: 3.99 },
    { id: "4", 
    name: "Guinness Extra Stout", 
    description: "Dry Stout",
    rating: 5.0,
    image: "https://wikiliq.org/wp-content/uploads/2021/02/Guinness-Extra-Stout.jpeg", 
    date: "01-01-1759",
    price: 10.49 },
    { id: "5", 
    name: "Beck's", 
    description: "Pilsner",
    rating: 5.0,
    image: "https://wikiliq.org/wp-content/uploads/2021/02/Beck8217s.jpeg", 
    date: "10-29-1873",
    price: 15.39 },
    { id: "6", 
    name: "LandShark Lager", 
    description: "Pale Lager",
    rating: 4.8,
    image: "https://wikiliq.org/wp-content/uploads/2021/02/LandShark-Lager.jpeg", 
    date: "01-21-2008",
    price: 14.99 },
    { id: "7", 
    name: "Amstel Light", 
    description: "Pale Lager",
    rating: 5.0,
    image: "https://wikiliq.org/wp-content/uploads/2021/02/Amstel-Light.jpeg", 
    date: "01-28-1870",
    price: 16.99 },
    { id: "8", 
    name: "Blue Moon Light Sky Wheat Beer", 
    description: "Wheat Ale",
    rating: 4.9,
    image: "https://wikiliq.org/wp-content/uploads/2021/02/Blue-Moon-Light-Sky-Wheat-Beer.jpeg", 
    date: "07-14-2020",
    price: 17.99 },
    { id: "9", 
    name: "Corona Extra Coronita", 
    description: "American-Style Lager",
    rating: 4.9,
    image: "https://wikiliq.org/wp-content/uploads/2021/02/Corona-Extra-Coronita.jpeg", 
    date: "08-12-1925",
    price: 23.99 },
    { id: "10", 
    name: "Tecate", 
    description: "Pale Lager/American-Style Lager",
    rating: 5.0,
    image: "https://wikiliq.org/wp-content/uploads/2021/02/Tecate.jpeg", 
    date: "03-01-2021",
    price: 12.99 }
]