module.exports.data = [ 
    { id: "1", 
    name: "Bud Light", 
    description: "American-Style Lager", 
    rating: 4.9,
    date: "05-10-1982" },
    { id: "2", 
    name: "Stella Artois", 
    description: "Pale Lager",
    rating: 5.0, 
    date: "01-22-1926" },
    { id: "3", 
    name: "New Belgium Fat Tire Amber Ale", 
    description: "Amber/Red Ale",
    rating: 5.0, 
    date: "11-22-1955" },
    { id: "4", 
    name: "Guinness Extra Stout", 
    description: "Dry Stout",
    rating: 5.0, 
    date: "01-01-1902" },
    { id: "5", 
    name: "Beck's", 
    description: "Pilsner",
    rating: 5.0, 
    date: "10-29-1970" },
    { id: "6", 
    name: "LandShark Lager", 
    description: "Pale Lager",
    rating: 5.0, 
    date: "01-21-1995" },
    { id: "7", 
    name: "Amstel Light", 
    description: "Pale Lager",
    rating: 5.0, 
    date: "01-28-1977" },
    { id: "8", 
    name: "Blue Moon Light Sky Wheat Beer", 
    description: "Wheat Ale",
    rating: 5.0, 
    date: "07-14-1988" },
    { id: "9", 
    name: "Corona Extra Coronita", 
    description: "American-Style Lager",
    rating: 5.0, 
    date: "08-12-1982" },
    { id: "10", 
    name: "Tecate", 
    description: "Pale Lager/American-Style Lager",
    rating: 5.0, 
    date: "03-01-1930" },
]